package es.jesmon.entities;
// Generated 21-may-2018 20:52:25 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * ContratoIncencidios generated by hbm2java
 */
@Entity
@Table(name = "contrato_incencidios", catalog = "jesmon")
@DynamicUpdate(value=true)
@DynamicInsert(value=true)

public class ContratoIncencidios implements java.io.Serializable {

	private static final long serialVersionUID = 7085433959810781664L;
	private int idContrato;
	private Empresa empresa;
	private Fichero fichero;
	private String numeroContrato;
	private Integer unidadesSistemaDeteccion;
	private Double precioUnitarioSistemaDeteccion;
	private Integer unidadesBocaIncendio;
	private Double precioUnitarioBocaIncendio;
	private Integer unidadesGrupoPresion;
	private Double precioUnitarioGrupoPresion;
	private Integer unidadesRevisionExtintor;
	private Double precioUnitarioRevisionExtintor;
	private Integer unidadesAlumbradoEmergencia;
	private Double precioUnitarioAlumbradoEmergencia;
	private Double total;
	private Byte lgInstalacion;
	private Byte lgMantenimiento;
	private String formaPago;
	private Set<EquipoIncendios> equipoIncendioses = new HashSet<EquipoIncendios>(0);

	public ContratoIncencidios() {
	}

	public ContratoIncencidios(int idContrato, Empresa empresa) {
		this.idContrato = idContrato;
		this.empresa = empresa;
	}

	public ContratoIncencidios(int idContrato, Empresa empresa, Fichero fichero, String numeroContrato,
			Integer unidadesSistemaDeteccion, Double precioUnitarioSistemaDeteccion, Integer unidadesBocaIncendio,
			Double precioUnitarioBocaIncendio, Integer unidadesGrupoPresion, Double precioUnitarioGrupoPresion,
			Integer unidadesRevisionExtintor, Double precioUnitarioRevisionExtintor,
			Integer unidadesAlumbradoEmergencia, Double precioUnitarioAlumbradoEmergencia, Double total,
			Byte lgInstalacion, Byte lgMantenimiento, String formaPago, Set<EquipoIncendios> equipoIncendioses) {
		this.idContrato = idContrato;
		this.empresa = empresa;
		this.fichero = fichero;
		this.numeroContrato = numeroContrato;
		this.unidadesSistemaDeteccion = unidadesSistemaDeteccion;
		this.precioUnitarioSistemaDeteccion = precioUnitarioSistemaDeteccion;
		this.unidadesBocaIncendio = unidadesBocaIncendio;
		this.precioUnitarioBocaIncendio = precioUnitarioBocaIncendio;
		this.unidadesGrupoPresion = unidadesGrupoPresion;
		this.precioUnitarioGrupoPresion = precioUnitarioGrupoPresion;
		this.unidadesRevisionExtintor = unidadesRevisionExtintor;
		this.precioUnitarioRevisionExtintor = precioUnitarioRevisionExtintor;
		this.unidadesAlumbradoEmergencia = unidadesAlumbradoEmergencia;
		this.precioUnitarioAlumbradoEmergencia = precioUnitarioAlumbradoEmergencia;
		this.total = total;
		this.lgInstalacion = lgInstalacion;
		this.lgMantenimiento = lgMantenimiento;
		this.formaPago = formaPago;
		this.equipoIncendioses = equipoIncendioses;
	}

	@Id

	@Column(name = "id_contrato", unique = true, nullable = false)
	public int getIdContrato() {
		return this.idContrato;
	}

	public void setIdContrato(int idContrato) {
		this.idContrato = idContrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fichero")
	public Fichero getFichero() {
		return this.fichero;
	}

	public void setFichero(Fichero fichero) {
		this.fichero = fichero;
	}

	@Column(name = "numero_contrato", length = 45)
	public String getNumeroContrato() {
		return this.numeroContrato;
	}

	public void setNumeroContrato(String numeroContrato) {
		this.numeroContrato = numeroContrato;
	}

	@Column(name = "unidades_sistema_deteccion")
	public Integer getUnidadesSistemaDeteccion() {
		return this.unidadesSistemaDeteccion;
	}

	public void setUnidadesSistemaDeteccion(Integer unidadesSistemaDeteccion) {
		this.unidadesSistemaDeteccion = unidadesSistemaDeteccion;
	}

	@Column(name = "precio_unitario_sistema_deteccion", precision = 22, scale = 0)
	public Double getPrecioUnitarioSistemaDeteccion() {
		return this.precioUnitarioSistemaDeteccion;
	}

	public void setPrecioUnitarioSistemaDeteccion(Double precioUnitarioSistemaDeteccion) {
		this.precioUnitarioSistemaDeteccion = precioUnitarioSistemaDeteccion;
	}

	@Column(name = "unidades_boca_incendio")
	public Integer getUnidadesBocaIncendio() {
		return this.unidadesBocaIncendio;
	}

	public void setUnidadesBocaIncendio(Integer unidadesBocaIncendio) {
		this.unidadesBocaIncendio = unidadesBocaIncendio;
	}

	@Column(name = "precio_unitario_boca_incendio", precision = 22, scale = 0)
	public Double getPrecioUnitarioBocaIncendio() {
		return this.precioUnitarioBocaIncendio;
	}

	public void setPrecioUnitarioBocaIncendio(Double precioUnitarioBocaIncendio) {
		this.precioUnitarioBocaIncendio = precioUnitarioBocaIncendio;
	}

	@Column(name = "unidades_grupo_presion")
	public Integer getUnidadesGrupoPresion() {
		return this.unidadesGrupoPresion;
	}

	public void setUnidadesGrupoPresion(Integer unidadesGrupoPresion) {
		this.unidadesGrupoPresion = unidadesGrupoPresion;
	}

	@Column(name = "precio_unitario_grupo_presion", precision = 22, scale = 0)
	public Double getPrecioUnitarioGrupoPresion() {
		return this.precioUnitarioGrupoPresion;
	}

	public void setPrecioUnitarioGrupoPresion(Double precioUnitarioGrupoPresion) {
		this.precioUnitarioGrupoPresion = precioUnitarioGrupoPresion;
	}

	@Column(name = "unidades_revision_extintor")
	public Integer getUnidadesRevisionExtintor() {
		return this.unidadesRevisionExtintor;
	}

	public void setUnidadesRevisionExtintor(Integer unidadesRevisionExtintor) {
		this.unidadesRevisionExtintor = unidadesRevisionExtintor;
	}

	@Column(name = "precio_unitario_revision_extintor", precision = 22, scale = 0)
	public Double getPrecioUnitarioRevisionExtintor() {
		return this.precioUnitarioRevisionExtintor;
	}

	public void setPrecioUnitarioRevisionExtintor(Double precioUnitarioRevisionExtintor) {
		this.precioUnitarioRevisionExtintor = precioUnitarioRevisionExtintor;
	}

	@Column(name = "unidades_alumbrado_emergencia")
	public Integer getUnidadesAlumbradoEmergencia() {
		return this.unidadesAlumbradoEmergencia;
	}

	public void setUnidadesAlumbradoEmergencia(Integer unidadesAlumbradoEmergencia) {
		this.unidadesAlumbradoEmergencia = unidadesAlumbradoEmergencia;
	}

	@Column(name = "precio_unitario_alumbrado_emergencia", precision = 22, scale = 0)
	public Double getPrecioUnitarioAlumbradoEmergencia() {
		return this.precioUnitarioAlumbradoEmergencia;
	}

	public void setPrecioUnitarioAlumbradoEmergencia(Double precioUnitarioAlumbradoEmergencia) {
		this.precioUnitarioAlumbradoEmergencia = precioUnitarioAlumbradoEmergencia;
	}

	@Column(name = "total", precision = 22, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Column(name = "lg_instalacion")
	public Byte getLgInstalacion() {
		return this.lgInstalacion;
	}

	public void setLgInstalacion(Byte lgInstalacion) {
		this.lgInstalacion = lgInstalacion;
	}

	@Column(name = "lg_mantenimiento")
	public Byte getLgMantenimiento() {
		return this.lgMantenimiento;
	}

	public void setLgMantenimiento(Byte lgMantenimiento) {
		this.lgMantenimiento = lgMantenimiento;
	}

	@Column(name = "forma_pago", length = 45)
	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(String formaPago) {
		this.formaPago = formaPago;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contratoIncencidios")
	public Set<EquipoIncendios> getEquipoIncendioses() {
		return this.equipoIncendioses;
	}

	public void setEquipoIncendioses(Set<EquipoIncendios> equipoIncendioses) {
		this.equipoIncendioses = equipoIncendioses;
	}

}
