package es.jesmon.entities;
// Generated 21-may-2018 20:52:25 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * ContratoSistemaSeguridad generated by hbm2java
 */
@Entity
@Table(name = "contrato_sistema_seguridad", catalog = "jesmon")
@DynamicUpdate(value=true)
@DynamicInsert(value=true)

public class ContratoSistemaSeguridad implements java.io.Serializable {

	private static final long serialVersionUID = -2527113018842488077L;
	private Integer idContrato;
	private Fichero fichero;
	private Empresa empresa;
	private Date fechaCc;
	private Date fechaCs;
	private Byte lgInstalacion;
	private Byte lgMantenimiento;
	private String formaPago;

	public ContratoSistemaSeguridad() {
	}

	public ContratoSistemaSeguridad(int idContrato, Empresa empresa) {
		this.idContrato = idContrato;
		this.empresa = empresa;
	}

	public ContratoSistemaSeguridad(Fichero fichero, Empresa empresa, Date fechaCc, Date fechaCs, Byte lgInstalacion,
			Byte lgMantenimiento, String formaPago) {
		this.fichero = fichero;
		this.empresa = empresa;
		this.fechaCc = fechaCc;
		this.fechaCs = fechaCs;
		this.lgInstalacion = lgInstalacion;
		this.lgMantenimiento = lgMantenimiento;
		this.formaPago = formaPago;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_contrato", unique = true, nullable = false)
	public Integer getIdContrato() {
		return this.idContrato;
	}

	public void setIdContrato(Integer idContrato) {
		this.idContrato = idContrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fichero")
	public Fichero getFichero() {
		return this.fichero;
	}

	public void setFichero(Fichero fichero) {
		this.fichero = fichero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_cc", length = 10)
	public Date getFechaCc() {
		return this.fechaCc;
	}

	public void setFechaCc(Date fechaCc) {
		this.fechaCc = fechaCc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_cs", length = 10)
	public Date getFechaCs() {
		return this.fechaCs;
	}

	public void setFechaCs(Date fechaCs) {
		this.fechaCs = fechaCs;
	}

	@Column(name = "lg_instalacion")
	public Byte getLgInstalacion() {
		return this.lgInstalacion;
	}

	public void setLgInstalacion(Byte lgInstalacion) {
		this.lgInstalacion = lgInstalacion;
	}

	@Column(name = "lg_mantenimiento")
	public Byte getLgMantenimiento() {
		return this.lgMantenimiento;
	}

	public void setLgMantenimiento(Byte lgMantenimiento) {
		this.lgMantenimiento = lgMantenimiento;
	}

	@Column(name = "forma_pago", length = 45)
	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(String formaPago) {
		this.formaPago = formaPago;
	}

}
