package es.jesmon.entities;
// Generated 21-may-2018 20:52:25 by Hibernate Tools 5.2.6.Final

import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * ContratoIncencidios generated by hbm2java
 */
@Entity
@Table(name = "contrato_incendios", catalog = "jesmon")
@DynamicUpdate(value=true)
@DynamicInsert(value=true)

public class ContratoIncendios implements java.io.Serializable {

	
	public static Byte TIPO_CONTRATO_INSTALACION = 0;
	public static Byte TIPO_CONTRATO_MANTENIMIENTO = 1;
	
	private static final long serialVersionUID = 7085433959810781664L;
	private int idContrato;
	private Empresa empresa;
	private FicheroBasico fichero;
	private String numeroContrato;
	private Integer unidadesSistemaDeteccion;
	private Double precioUnitarioSistemaDeteccion;
	private Integer unidadesBocaIncendio;
	private Double precioUnitarioBocaIncendio;
	private Integer unidadesGrupoPresion;
	private Double precioUnitarioGrupoPresion;
	private Integer unidadesRevisionExtintor;
	private Double precioUnitarioRevisionExtintor;
	private Integer unidadesAlumbradoEmergencia;
	private Double precioUnitarioAlumbradoEmergencia;
	private Double total;
	/*
	private Byte lgInstalacion;
	private Byte lgMantenimiento;*/
	
	private Byte tipoContrato;
	private String formaPago;
	private Date fechaContrato;
	private Set<EquipoIncendios> equiposIncendios = new HashSet<EquipoIncendios>(0);

	public ContratoIncendios() {
	}

	public ContratoIncendios(int idContrato, Empresa empresa) {
		this.idContrato = idContrato;
		this.empresa = empresa;
	}

	public ContratoIncendios(int idContrato, Empresa empresa, FicheroBasico fichero, String numeroContrato,
			Integer unidadesSistemaDeteccion, Double precioUnitarioSistemaDeteccion, Integer unidadesBocaIncendio,
			Double precioUnitarioBocaIncendio, Integer unidadesGrupoPresion, Double precioUnitarioGrupoPresion,
			Integer unidadesRevisionExtintor, Double precioUnitarioRevisionExtintor,
			Integer unidadesAlumbradoEmergencia, Double precioUnitarioAlumbradoEmergencia, Double total,
			Byte tipoContrato, String formaPago, Set<EquipoIncendios> equiposIncendios) {
		this.idContrato = idContrato;
		this.empresa = empresa;
		this.fichero = fichero;
		this.numeroContrato = numeroContrato;
		this.unidadesSistemaDeteccion = unidadesSistemaDeteccion;
		this.precioUnitarioSistemaDeteccion = precioUnitarioSistemaDeteccion;
		this.unidadesBocaIncendio = unidadesBocaIncendio;
		this.precioUnitarioBocaIncendio = precioUnitarioBocaIncendio;
		this.unidadesGrupoPresion = unidadesGrupoPresion;
		this.precioUnitarioGrupoPresion = precioUnitarioGrupoPresion;
		this.unidadesRevisionExtintor = unidadesRevisionExtintor;
		this.precioUnitarioRevisionExtintor = precioUnitarioRevisionExtintor;
		this.unidadesAlumbradoEmergencia = unidadesAlumbradoEmergencia;
		this.precioUnitarioAlumbradoEmergencia = precioUnitarioAlumbradoEmergencia;
		this.total = total;
		this.tipoContrato = tipoContrato;
		this.formaPago = formaPago;
		this.equiposIncendios = equiposIncendios;
	}

	@Id

	@Column(name = "id_contrato", unique = true, nullable = false)
	public int getIdContrato() {
		return this.idContrato;
	}

	public void setIdContrato(int idContrato) {
		this.idContrato = idContrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fichero")
	public FicheroBasico getFichero() {
		return this.fichero;
	}

	public void setFichero(FicheroBasico fichero) {
		this.fichero = fichero;
	}

	@Column(name = "numero_contrato", length = 45)
	public String getNumeroContrato() {
		return this.numeroContrato;
	}

	public void setNumeroContrato(String numeroContrato) {
		this.numeroContrato = numeroContrato;
	}

	@Column(name = "unidades_sistema_deteccion")
	public Integer getUnidadesSistemaDeteccion() {
		return this.unidadesSistemaDeteccion;
	}

	public void setUnidadesSistemaDeteccion(Integer unidadesSistemaDeteccion) {
		this.unidadesSistemaDeteccion = unidadesSistemaDeteccion;
	}

	@Column(name = "precio_unitario_sistema_deteccion", precision = 22, scale = 0)
	public Double getPrecioUnitarioSistemaDeteccion() {
		return this.precioUnitarioSistemaDeteccion;
	}

	public void setPrecioUnitarioSistemaDeteccion(Double precioUnitarioSistemaDeteccion) {
		this.precioUnitarioSistemaDeteccion = precioUnitarioSistemaDeteccion;
	}

	@Column(name = "unidades_boca_incendio")
	public Integer getUnidadesBocaIncendio() {
		return this.unidadesBocaIncendio;
	}

	public void setUnidadesBocaIncendio(Integer unidadesBocaIncendio) {
		this.unidadesBocaIncendio = unidadesBocaIncendio;
	}

	@Column(name = "precio_unitario_boca_incendio", precision = 22, scale = 0)
	public Double getPrecioUnitarioBocaIncendio() {
		return this.precioUnitarioBocaIncendio;
	}

	public void setPrecioUnitarioBocaIncendio(Double precioUnitarioBocaIncendio) {
		this.precioUnitarioBocaIncendio = precioUnitarioBocaIncendio;
	}

	@Column(name = "unidades_grupo_presion")
	public Integer getUnidadesGrupoPresion() {
		return this.unidadesGrupoPresion;
	}

	public void setUnidadesGrupoPresion(Integer unidadesGrupoPresion) {
		this.unidadesGrupoPresion = unidadesGrupoPresion;
	}

	@Column(name = "precio_unitario_grupo_presion", precision = 22, scale = 0)
	public Double getPrecioUnitarioGrupoPresion() {
		return this.precioUnitarioGrupoPresion;
	}

	public void setPrecioUnitarioGrupoPresion(Double precioUnitarioGrupoPresion) {
		this.precioUnitarioGrupoPresion = precioUnitarioGrupoPresion;
	}

	@Column(name = "unidades_revision_extintor")
	public Integer getUnidadesRevisionExtintor() {
		return this.unidadesRevisionExtintor;
	}

	public void setUnidadesRevisionExtintor(Integer unidadesRevisionExtintor) {
		this.unidadesRevisionExtintor = unidadesRevisionExtintor;
	}

	@Column(name = "precio_unitario_revision_extintor", precision = 22, scale = 0)
	public Double getPrecioUnitarioRevisionExtintor() {
		return this.precioUnitarioRevisionExtintor;
	}

	public void setPrecioUnitarioRevisionExtintor(Double precioUnitarioRevisionExtintor) {
		this.precioUnitarioRevisionExtintor = precioUnitarioRevisionExtintor;
	}

	@Column(name = "unidades_alumbrado_emergencia")
	public Integer getUnidadesAlumbradoEmergencia() {
		return this.unidadesAlumbradoEmergencia;
	}

	public void setUnidadesAlumbradoEmergencia(Integer unidadesAlumbradoEmergencia) {
		this.unidadesAlumbradoEmergencia = unidadesAlumbradoEmergencia;
	}

	@Column(name = "precio_unitario_alumbrado_emergencia", precision = 22, scale = 0)
	public Double getPrecioUnitarioAlumbradoEmergencia() {
		return this.precioUnitarioAlumbradoEmergencia;
	}

	public void setPrecioUnitarioAlumbradoEmergencia(Double precioUnitarioAlumbradoEmergencia) {
		this.precioUnitarioAlumbradoEmergencia = precioUnitarioAlumbradoEmergencia;
	}

	@Column(name = "total", precision = 22, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Column(name = "tipo_contrato")
	public Byte getTipoContrato() {
		return this.tipoContrato;
	}

	public void setTipoContrato(Byte tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	@Column(name = "forma_pago", length = 45)
	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(String formaPago) {
		this.formaPago = formaPago;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contratoIncendios")
	public Set<EquipoIncendios> getEquiposIncendios() {
		return this.equiposIncendios;
	}

	public void setEquiposIncendios(Set<EquipoIncendios> equiposIncendios) {
		this.equiposIncendios = equiposIncendios;
	}

	@Transient
	public List<EquipoIncendios> getListaEquiposIncendios (){
		List<EquipoIncendios> listaEquipoIncendios = new ArrayList<EquipoIncendios>(equiposIncendios);
		listaEquipoIncendios.sort(Comparator.comparing(EquipoIncendios::getIdEquipo).reversed());
		return listaEquipoIncendios;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_contrato", length = 10)
	public Date getFechaContrato() {
		return fechaContrato;
	}

	public void setFechaContrato(Date fechaContrato) {
		this.fechaContrato = fechaContrato;
	}

}
