package es.jesmon.entities;
// Generated 29-ene-2018 22:17:55 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "direccion", catalog = "jesmon")
public class Direccion implements java.io.Serializable {

	private static final long serialVersionUID = -2057353832009836086L;
	private Integer idDireccion;
	private Provincia provincia;
	private String municipio;
	private String direccion;
	private String codigoPostal;
	private Set<Sede> sedes = new HashSet<Sede>(0);

	public Direccion() {
	}

	public Direccion(Provincia provincia, String municipio, String direccion) {
		this.provincia = provincia;
		this.municipio = municipio;
		this.direccion = direccion;
	}

	public Direccion(Provincia provincia, String municipio, String direccion, String codigoPostal, Set<Sede> sedes) {
		this.provincia = provincia;
		this.municipio = municipio;
		this.direccion = direccion;
		this.codigoPostal = codigoPostal;
		this.sedes = sedes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_direccion", unique = true, nullable = false)
	public Integer getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Integer idDireccion) {
		this.idDireccion = idDireccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cd_provincia", nullable = false)
	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	@Column(name = "municipio", nullable = false, length = 100)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "direccion", nullable = false, length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "codigo_postal", length = 5)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccion")
	public Set<Sede> getSedes() {
		return this.sedes;
	}

	public void setSedes(Set<Sede> sedes) {
		this.sedes = sedes;
	}

}
