package es.jesmon.entities;
// Generated 21-may-2018 20:52:25 by Hibernate Tools 5.2.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * EquipoIncendios generated by hbm2java
 */
@Entity
@Table(name = "equipo_incendios", catalog = "jesmon")
@DynamicUpdate(value=true)
@DynamicInsert(value=true)

public class EquipoIncendios implements java.io.Serializable {

	private static List<String> listaElementos = new ArrayList<String>(); 
	
	private static final long serialVersionUID = -121490754592431657L;
	private Integer idEquipo;
	private ContratoIncendios contratoIncendios;
	private Integer unidades;
	private String elemento;
	private Double peso;
	private String ubicacion;
	private Integer fechaFabricacion;
	private Integer fechaRetimbrado;
	private String numeroSerie;
	
	static {
		listaElementos.add("BIE");
		listaElementos.add("Espumógeno");
		listaElementos.add("Extintor ABC");
		listaElementos.add("Extintor CO2");
	}

	public EquipoIncendios() {
	}

	public EquipoIncendios(ContratoIncendios contratoIncendios) {
		this.contratoIncendios = contratoIncendios;
	}

	public EquipoIncendios(ContratoIncendios contratoIncendios, Integer unidades, String elemento, Double peso,
			String ubicacion, Integer fechaFabricacion, Integer fechaRetimbrado, String numeroSerie) {
		this.contratoIncendios = contratoIncendios;
		this.unidades = unidades;
		this.elemento = elemento;
		this.peso = peso;
		this.ubicacion = ubicacion;
		this.fechaFabricacion = fechaFabricacion;
		this.fechaRetimbrado = fechaRetimbrado;
		this.numeroSerie = numeroSerie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_equipo", unique = true, nullable = false)
	public Integer getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contrato", nullable = false)
	public ContratoIncendios getContratoIncendios() {
		return this.contratoIncendios;
	}

	public void setContratoIncendios(ContratoIncendios contratoIncendios) {
		this.contratoIncendios = contratoIncendios;
	}

	@Column(name = "unidades")
	public Integer getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Integer unidades) {
		this.unidades = unidades;
	}

	@Column(name = "elemento", length = 100)
	public String getElemento() {
		return this.elemento;
	}

	public void setElemento(String elemento) {
		this.elemento = elemento;
	}

	@Column(name = "peso", precision = 22, scale = 0)
	public Double getPeso() {
		return this.peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	@Column(name = "ubicacion", length = 200)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "fecha_fabricacion")
	public Integer getFechaFabricacion() {
		return this.fechaFabricacion;
	}

	public void setFechaFabricacion(Integer fechaFabricacion) {
		this.fechaFabricacion = fechaFabricacion;
	}

	@Column(name = "fecha_retimbrado")
	public Integer getFechaRetimbrado() {
		return this.fechaRetimbrado;
	}

	public void setFechaRetimbrado(Integer fechaRetimbrado) {
		this.fechaRetimbrado = fechaRetimbrado;
	}

	@Column(name = "numero_serie", length = 50)
	public String getNumeroSerie() {
		return this.numeroSerie;
	}

	public void setNumeroSerie(String numeroSerie) {
		this.numeroSerie = numeroSerie;
	}

	public static List<String> getListaElementos() {
		return listaElementos;
	}

	public static void setListaElementos(List<String> listaElementos) {
		EquipoIncendios.listaElementos = listaElementos;
	}

}
