package es.jesmon.entities;
// Generated 21-may-2018 20:52:25 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * EquipoIncendios generated by hbm2java
 */
@Entity
@Table(name = "equipo_incendios", catalog = "jesmon")
@DynamicUpdate(value=true)
@DynamicInsert(value=true)

public class EquipoIncendios implements java.io.Serializable {

	private static final long serialVersionUID = -121490754592431657L;
	private Integer idEquipo;
	private ContratoIncencidios contratoIncencidios;
	private Integer unidades;
	private String elemento;
	private Double peso;
	private String ubicacion;
	private Date fechaFabricacion;
	private Date fechaRetimbrado;
	private String numeroSerie;

	public EquipoIncendios() {
	}

	public EquipoIncendios(ContratoIncencidios contratoIncencidios) {
		this.contratoIncencidios = contratoIncencidios;
	}

	public EquipoIncendios(ContratoIncencidios contratoIncencidios, Integer unidades, String elemento, Double peso,
			String ubicacion, Date fechaFabricacion, Date fechaRetimbrado, String numeroSerie) {
		this.contratoIncencidios = contratoIncencidios;
		this.unidades = unidades;
		this.elemento = elemento;
		this.peso = peso;
		this.ubicacion = ubicacion;
		this.fechaFabricacion = fechaFabricacion;
		this.fechaRetimbrado = fechaRetimbrado;
		this.numeroSerie = numeroSerie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_equipo", unique = true, nullable = false)
	public Integer getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contrato", nullable = false)
	public ContratoIncencidios getContratoIncencidios() {
		return this.contratoIncencidios;
	}

	public void setContratoIncencidios(ContratoIncencidios contratoIncencidios) {
		this.contratoIncencidios = contratoIncencidios;
	}

	@Column(name = "unidades")
	public Integer getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Integer unidades) {
		this.unidades = unidades;
	}

	@Column(name = "elemento", length = 100)
	public String getElemento() {
		return this.elemento;
	}

	public void setElemento(String elemento) {
		this.elemento = elemento;
	}

	@Column(name = "peso", precision = 22, scale = 0)
	public Double getPeso() {
		return this.peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	@Column(name = "ubicacion", length = 200)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fabricacion", length = 10)
	public Date getFechaFabricacion() {
		return this.fechaFabricacion;
	}

	public void setFechaFabricacion(Date fechaFabricacion) {
		this.fechaFabricacion = fechaFabricacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_retimbrado", length = 10)
	public Date getFechaRetimbrado() {
		return this.fechaRetimbrado;
	}

	public void setFechaRetimbrado(Date fechaRetimbrado) {
		this.fechaRetimbrado = fechaRetimbrado;
	}

	@Column(name = "numero_serie", length = 50)
	public String getNumeroSerie() {
		return this.numeroSerie;
	}

	public void setNumeroSerie(String numeroSerie) {
		this.numeroSerie = numeroSerie;
	}

}
