package es.jesmon.entities;
// Generated 29-ene-2018 22:17:55 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Estado generated by hbm2java
 */
@Entity
@Cacheable
@Table(name = "estado", catalog = "jesmon")
public class Estado implements java.io.Serializable {

	private static final long serialVersionUID = -8664565560592056088L;
	private Integer idEstado;
	private Integer orden;
	private String descripcion;
	private Set<EstadoIncidencia> estadoIncidencias = new HashSet<EstadoIncidencia>(0);

	public static Integer ESTADO_PENDIENTE = 1;
	public static Integer ESTADO_EN_TRAMITE = 2;
	public static Integer ESTADO_RESUELTA = 3;
	public static Integer ESTADO_CANCELADA = 4;
	
	public Estado() {
	}
	
	public Estado(Integer idEstado) {
		this.idEstado = idEstado;
	}

	public Estado(Integer idEstado, String descripcion) {
		this.idEstado = idEstado;
		this.descripcion = descripcion;
	}

	public Estado(Integer idEstado, String descripcion, Set<EstadoIncidencia> estadoIncidencias) {
		this.idEstado = idEstado;
		this.descripcion = descripcion;
		this.estadoIncidencias = estadoIncidencias;
	}

	@Id

	@Column(name = "id_estado", unique = true, nullable = false)
	public Integer getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Integer idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<EstadoIncidencia> getEstadoIncidencias() {
		return this.estadoIncidencias;
	}

	public void setEstadoIncidencias(Set<EstadoIncidencia> estadoIncidencias) {
		this.estadoIncidencias = estadoIncidencias;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	//https://getbootstrap.com/docs/4.0/utilities/colors/
	@Transient
	public String getClassCss() {
		if(idEstado.equals(ESTADO_PENDIENTE))
			return "text-primary";
		else if(idEstado.equals(ESTADO_EN_TRAMITE))
			return "text-info";
		else if(idEstado.equals(ESTADO_RESUELTA))
			return "text-success";
		else if(idEstado.equals(ESTADO_CANCELADA))
			return "text-warning";
		return "";
		
	}
}
