package es.jesmon.entities;
// Generated 17-abr-2018 23:59:25 by Hibernate Tools 5.2.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import java.util.Base64;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Fichero generated by hbm2java
 */
@Entity
@Table(name = "fichero", catalog = "jesmon")
public class FicheroBasico implements java.io.Serializable {

	private static final long serialVersionUID = -5561405374947392121L;
	private Integer idFichero;
	private String nombreFichero;
	private Set<EstadoIncidencia> estadoIncidencias = new HashSet<EstadoIncidencia>(0);
	private Set<Mensaje> mensajes = new HashSet<Mensaje>(0);

	public FicheroBasico() {
	}

	public FicheroBasico(String nombreFichero) {
		this.nombreFichero = nombreFichero;
	}

	public FicheroBasico(String nombreFichero, byte[] contenidoFichero, Set<EstadoIncidencia> estadoIncidencias,
			Set<Mensaje> mensajes) {
		this.nombreFichero = nombreFichero;
		this.estadoIncidencias = estadoIncidencias;
		this.mensajes = mensajes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_fichero", unique = true, nullable = false)
	public Integer getIdFichero() {
		return this.idFichero;
	}

	public void setIdFichero(Integer idFichero) {
		this.idFichero = idFichero;
	}
	
	@Transient
	public String getIdFicheroB64() {
		return Base64.getEncoder().encodeToString(idFichero.toString().getBytes());
	}

	@Column(name = "nombre_fichero", nullable = false, length = 100)
	public String getNombreFichero() {
		return this.nombreFichero;
	}

	public void setNombreFichero(String nombreFichero) {
		this.nombreFichero = nombreFichero;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "rel_fichero_estado_incidecia", catalog = "jesmon", joinColumns = {
			@JoinColumn(name = "id_fichero", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_estado", nullable = false, updatable = false) })
	public Set<EstadoIncidencia> getEstadoIncidencias() {
		return this.estadoIncidencias;
	}

	public void setEstadoIncidencias(Set<EstadoIncidencia> estadoIncidencias) {
		this.estadoIncidencias = estadoIncidencias;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "rel_fichero_mensaje", catalog = "jesmon", joinColumns = {
			@JoinColumn(name = "id_fichero", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_mensaje", nullable = false, updatable = false) })
	public Set<Mensaje> getMensajes() {
		return this.mensajes;
	}

	public void setMensajes(Set<Mensaje> mensajes) {
		this.mensajes = mensajes;
	}

}
