package es.jesmon.entities;
// Generated 29-ene-2018 22:17:55 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mensaje generated by hbm2java
 */
@Entity
@Table(name = "mensaje", catalog = "jesmon")
public class Mensaje implements java.io.Serializable {

	private static final long serialVersionUID = 3388555864537005273L;
	private Integer idMensaje;
	private Incidencia incidencia;
	private Responsable responsable;
	private Tramitador tramitador;
	private Date fecha;
	private String texto;
	private Integer lgInterno;

	public Mensaje() {
	}

	public Mensaje(Incidencia incidencia, Date fecha, String texto) {
		this.incidencia = incidencia;
		this.fecha = fecha;
		this.texto = texto;
	}

	public Mensaje(Incidencia incidencia, Responsable responsable, Tramitador tramitador, Date fecha, String texto,
			Integer lgInterno) {
		this.incidencia = incidencia;
		this.responsable = responsable;
		this.tramitador = tramitador;
		this.fecha = fecha;
		this.texto = texto;
		this.lgInterno = lgInterno;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_mensaje", unique = true, nullable = false)
	public Integer getIdMensaje() {
		return this.idMensaje;
	}

	public void setIdMensaje(Integer idMensaje) {
		this.idMensaje = idMensaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_incidencia", nullable = false)
	public Incidencia getIncidencia() {
		return this.incidencia;
	}

	public void setIncidencia(Incidencia incidencia) {
		this.incidencia = incidencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_reponsable")
	public Responsable getResponsable() {
		return this.responsable;
	}

	public void setResponsable(Responsable responsable) {
		this.responsable = responsable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tramitador")
	public Tramitador getTramitador() {
		return this.tramitador;
	}

	public void setTramitador(Tramitador tramitador) {
		this.tramitador = tramitador;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "texto", nullable = false, length = 4000)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "lg_interno")
	public Integer getLgInterno() {
		return this.lgInterno;
	}

	public void setLgInterno(Integer lgInterno) {
		this.lgInterno = lgInterno;
	}

}
