package es.jesmon.entities;
// Generated 29-ene-2018 22:17:55 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name = "provincia", catalog = "jesmon")
public class Provincia implements java.io.Serializable {

	private static final long serialVersionUID = -5808173760648521979L;
	private String cdProvincia;
	private String denominacion;
	private Set<Direccion> direccions = new HashSet<Direccion>(0);

	public Provincia() {
	}

	public Provincia(String cdProvincia, String denominacion) {
		this.cdProvincia = cdProvincia;
		this.denominacion = denominacion;
	}

	public Provincia(String cdProvincia, String denominacion, Set<Direccion> direccions) {
		this.cdProvincia = cdProvincia;
		this.denominacion = denominacion;
		this.direccions = direccions;
	}

	@Id

	@Column(name = "cd_provincia", unique = true, nullable = false, length = 2)
	public String getCdProvincia() {
		return this.cdProvincia;
	}

	public void setCdProvincia(String cdProvincia) {
		this.cdProvincia = cdProvincia;
	}

	@Column(name = "denominacion", nullable = false, length = 100)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincia")
	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

}
